#!/bin/bash
echo "-----------------------------------------------------------------------"
echo "Create sym links"
ln -sf /usr/share/dizaines/dizaines.py /usr/bin/dizaines
echo "Symbolic links created."
ls -l /usr/bin/dizaines
echo "-----------------------------------------------------------------------"
exit 0
